## Perceptron

Nomes: Fernando Veizaga, Gabriel Siqueira

In [17]:
import pandas as pd
import numpy as np

data = pd.read_csv('Iris_Data.csv', sep=',', header=0)

classes = np.repeat(["[1 0 0]", "[0 1 0]", "[0 0 1]"], 50)
data_with_classes = data.assign(Class=classes)
data_with_classes.to_csv("Iris_Data_Classes.csv", index=False)
data = pd.read_csv('Iris_Data_Classes.csv', sep=',', header=0)
data

sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

       Class  
0    [1 0 0]  
1    [1 0 0]  
2    [1 0 0]  
3    [1 0 0]  
4    [1 0 0]  
..       ...  
145  [0 0 1]  
146  [0 0 1]  
147  [0 0 1]  
148  [0 0 1]  
149  [0 0 1]  

[150 rows x 6 columns]

In [42]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(data, test_size=0.3, random_state=42)

X_train = train_data.iloc[:, :-2].values
y_train = train_data.iloc[:, -1].values
X_test = test_data.iloc[:, :-2].values
y_test = test_data.iloc[:, -1].values

np.transpose(X_train)

array([[5.5, 6.3, 6.4, 6.6, 7.2, 5.7, 7.6, 5.6, 5.1, 7.7, 5.8, 5.2, 5. ,
        5.1, 5. , 6.3, 4.8, 5. , 5.1, 5.6, 5.1, 5.7, 7.7, 4.6, 6.2, 5.7,
        5.5, 6. , 5.8, 6. , 5.4, 6.2, 5.5, 5.4, 5. , 6.4, 5. , 5. , 5.5,
        6.7, 4.9, 5.8, 5. , 5. , 5.9, 5.1, 6.9, 6. , 6.1, 7.7, 5.5, 4.4,
        4.3, 6. , 7.2, 4.6, 5.1, 4.4, 6.3, 6.3, 4.6, 6.8, 6.3, 4.7, 6.1,
        6.5, 6.2, 7. , 6.4, 5.1, 6.9, 5.9, 6.5, 5.7, 5.2, 6.1, 4.5, 6.6,
        5.5, 5.3, 5.6, 7.3, 6.7, 5.1, 4.9, 6.7, 7.2, 4.9, 6.7, 4.9, 6.9,
        7.4, 6.3, 5.7, 6.5, 6.3, 6.4, 5.6, 5.9, 5.4, 6.1, 4.9, 5.8, 5.8,
        7.1],
       [2.4, 2.8, 3.1, 3. , 3.6, 2.9, 3. , 3. , 3.5, 2.8, 2.7, 3.4, 3.5,
        3.8, 2. , 2.7, 3.4, 3. , 3.3, 2.7, 3.4, 3. , 3.8, 3.2, 2.9, 2.5,
        4.2, 3. , 2.7, 2.2, 3. , 3.4, 2.3, 3.9, 2.3, 2.7, 3.3, 3.2, 2.4,
        3. , 3.1, 2.8, 3.4, 3.5, 3.2, 2.5, 3.2, 2.7, 2.6, 3. , 2.5, 2.9,
        3. , 2.2, 3.2, 3.1, 3.5, 3. , 2.5, 3.4, 3.4, 3. , 3.3, 3.2, 2.9,
        2.8, 2.8, 3.2, 3.2, 3.8, 3.1,

In [43]:
X_train

array([[5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2

In [44]:
y_train

array(['[0 1 0]', '[0 0 1]', '[0 0 1]', '[0 1 0]', '[0 0 1]', '[0 1 0]',
       '[0 0 1]', '[0 1 0]', '[1 0 0]', '[0 0 1]', '[0 1 0]', '[1 0 0]',
       '[1 0 0]', '[1 0 0]', '[0 1 0]', '[0 0 1]', '[1 0 0]', '[1 0 0]',
       '[1 0 0]', '[0 1 0]', '[1 0 0]', '[0 1 0]', '[0 0 1]', '[1 0 0]',
       '[0 1 0]', '[0 0 1]', '[1 0 0]', '[0 0 1]', '[0 0 1]', '[0 1 0]',
       '[0 1 0]', '[0 0 1]', '[0 1 0]', '[1 0 0]', '[0 1 0]', '[0 0 1]',
       '[1 0 0]', '[1 0 0]', '[0 1 0]', '[0 1 0]', '[1 0 0]', '[0 0 1]',
       '[1 0 0]', '[1 0 0]', '[0 1 0]', '[0 1 0]', '[0 0 1]', '[0 1 0]',
       '[0 0 1]', '[0 0 1]', '[0 1 0]', '[1 0 0]', '[1 0 0]', '[0 0 1]',
       '[0 0 1]', '[1 0 0]', '[1 0 0]', '[1 0 0]', '[0 1 0]', '[0 0 1]',
       '[1 0 0]', '[0 0 1]', '[0 0 1]', '[1 0 0]', '[0 1 0]', '[0 1 0]',
       '[0 0 1]', '[0 1 0]', '[0 0 1]', '[1 0 0]', '[0 0 1]', '[0 1 0]',
       '[0 0 1]', '[0 1 0]', '[0 1 0]', '[0 1 0]', '[1 0 0]', '[0 1 0]',
       '[0 1 0]', '[1 0 0]', '[0 1 0]', '[0 0 1]', 

In [45]:
for i in range (0,len(y_train)):
    s = y_train[i].replace("[", "").replace("]", "")
    elements = s.split(" ")
    y_train[i] = np.array([int(e) for e in elements])
    print(y_train[i])

y_train

[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]


array([array([0, 1, 0]), array([0, 0, 1]), array([0, 0, 1]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0]),
       array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0]),
       array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0]),
       array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0]),
       array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0]),
       array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0]),
       array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1]),
       array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0]),
       array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1]),
       array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 0, 1]),

In [ ]:
NEURON = 3
INPUT = 4

### Função de ativação

In [ ]:
def f(X, bias, p):
    
    y = np.zeros(1, len(X))
    
    if p == 1 :
        for i in range len(X):
            if(X[i][0] + bias >= 0):
                y[0][i] = 1
            else:
                y[0][i] = 0
    
    elif p == 2:
        for i in range len(X):
            y[0][i] = 1/(1+np.exp(-X[i][0]))
            
    elif p == 3:
        for i in range len(X):
            y[0][i] = 1/(1+np.exp(-X[i][0]))
        for i in range len(X):
            if(y[0][i] == max(y)):
                y[0][i] = 1
            else:
                y[0][i] = 0
                
    else:
        
            
    return y

def initialize(X):
    for i in range len(X[0]):
        for j in range len(X):
            X[j][i] = random(-1, 1)

### Algoritmo de Aprendizagem

In [ ]:
def perceptron(it, alpha, X, D, p):
    W = np.zeros(NEURON,INPUT)
    W = initialize(W)
    bias = np.zeros(NEURON,1)
    bias = initialize(bias)
    y = np.zeros(NEURON, 1)
    
    t = 1
    E = 1
    
    Epoca = np.zeros(it, 1)
    
    while t < it and E > 0:
        E = 0
        for i in range(1, len(X[0])):
            
            I = [X[i] for i in X]
            y = f(np.matmul(W, np.transpose(I)), bias, p)
            
            A = [D[i] for i in D]
            e = A - y
            
            W = W + alpha*e*I
            bias = bias + alpha*e
            E = E + sum([x**2 for x in e])
            
        Epoca[t] = E
        t = t + 1